### ISSUE TITLE
Error connecting to LuxuryNitro API: Unauthenticated.

### ISSUE THREAD

**Issue by jxmes7** [itschasa/LuxuryNitro-Reseller#3]
C:\Users\Administrator\Desktop\LuxuryNitro-Reseller-main>main.py
Coded with <3 by chasa | https://github.com/itschasa/LuxuryNitro-Reseller
If you have any issues, create an issue using the link above. :D

Connecting to LuxuryNitro API...
Error connecting to LuxuryNitro API (https://luxurynitro.com/api/v1): Unauthenticated.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000297BC561EA0>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

C:\Users\Administrator\Desktop\LuxuryNitro-Reseller-main>

**Comment by itschasa** [comment]
Please check your API key for the LuxuryNitro API is valid in your config.yml found here:

https://github.com/itschasa/LuxuryNitro-Reseller/blob/main/config.yml#L7

**Comment by itschasa** [comment]
Please check your API key for the LuxuryNitro API is valid in your config.yml found here:

https://github.com/itschasa/LuxuryNitro-Reseller/blob/main/config.yml?plain=1#L7

**Comment by itschasa** [comment]
Can you double check that it is pasted correctly? It wouldn't give this error for no reason.

**Comment by jxmes7** [comment]
# https://luxurynitro.com/settings
api_key: ayoa3PimtsWB2bKpj6oINHF5LdjnQxDeYETJW2xuTZ55XY22Gq7E1ZSBd1pxEQTMck7307eqC

added and changed the few letter so didnt leak

**Comment by itschasa** [comment]
All api keys begin with `api_`, so something must be going wrong. Did you remove the `api_` part just for this post?

**Comment by jxmes7** [comment]
there no api in front of it i reset but now it does must of been glitched thanks for time

**Comment by itschasa** [comment]
Seems like its fixed now, the takeaway from this issue is that make sure you have `api_` at the front of your API key.
